# name
name: Main_Workflows

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main, action]
  workflow_dispatch:
    inputs:
      environment:
        description: '배포 환경'
        required: true
        default: 'staging'

# job
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: print hello
        run: echo "test"